name: security

on:
  push:
    branches:
      - master
    paths:
      - 'ExchangeRateTests/SecurityTests/**'
  pull_request:
    branches:
      - master
    paths:
      - 'ExchangeRateTests/SecurityTests/**'
  workflow_dispatch:

jobs:
  SecurityTests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SecurityTests
        run: |
          docker build -t exchange-security-tests -f ./ExchangeRateTests/SecurityTests/securitytests.dockerFile ./ExchangeRateTests
          docker run exchange-security-tests GBP
